spring.application.name: demo-service
server.port: 8080
security.basic.enabled: false
eureka:
  client.serviceUrl.defaultZone: ${eureka.url:http://localhost:8761}/eureka

user.service.url: http://localhost:8000
